repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ["--branch", "main"]
